name: reusable deployment workflow

on:
  workflow_call:
    secrets:
      DASH_SSH_KEY:
        required: true
      DASH_ENTERPRISE_URL:
        required: true
      APP_NAME:
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Add git remote
        run: git remote add plotly git@$DASH_ENTERPRISE_URL:$APP_NAME
        env:
          DASH_ENTERPRISE_URL: ${{secrets.DASH_ENTERPRISE_URL}}
          APP_NAME: ${{secrets.APP_NAME}}
      - name: Setup project directory
        run: |
          set -x
          pwd
          ls -al
          mkdir -p /home/runner/.ssh
      - name: Setup SSH key
        run: |
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa # permissioning
          eval "$(ssh-agent -s)" # setting ssh environment variable
          ssh-add ~/.ssh/id_rsa
          echo "Host *
              Port 22
              StrictHostKeyChecking no
              UserKnownHostsFile=/dev/null" > ~/.ssh/config
        env:
          SSH_PRIVATE_KEY: ${{secrets.DASH_SSH_KEY}}
      - name: Deploy
        run: |
          git push --force plotly HEAD:refs/heads/master
