name: production deployment

on:
  push:
    branches: [main]

jobs:
  prod-deploy:
    uses: ./.github/workflows/deploy.yml
    secrets:
      DASH_SSH_KEY: ${{secrets.DASH_SSH_KEY}}
      APP_NAME: ${{secrets.APP_NAME}}
      DASH_ENTERPRISE_URL: ${{secrets.DASH_ENTERPRISE_URL}}